### ISSUE TITLE
STATEMENT BY AUTHOR page is incorrect

### ISSUE THREAD

**Issue by yoursunny** [trananh/uathesis#1]
**STATEMENT BY AUTHOR** page generated by this template contains a CreativeCommons license statement, but as of 2017, the graduate college requires a different sample page that states:

> Requests for permission for extended quotation from or reproduction of this manuscript in whole or in part may be granted by the head of the major department or the Dean of the Graduate College when in his or her judgment the proposed use of the material is in the interests of scholarship.  In all other instances, however, permission must be obtained from the author.

http://grad.arizona.edu/gsas/dissertations-theses/sample-pages

**Comment by trananh** [comment]
The example does use a CC license, but there is also an option for no copyright. See link below. Also check comment just above it for other copyright options that you can use. Most (if not all) of these will be acceptable.

https://github.com/trananh/uathesis/blob/a4887cdf9dadb1d5873964776894e747c7f01f5d/dissertation.tex#L20

Edit: Feel free to reopen this issue if you find that the no copyright option also does not match the current template.

**Comment by yoursunny** [comment]
I discovered the "no copyright" option later and submitted my dissertation. The grad college gave the following feedback:
> 1. On your Title page: Under the rule line, add “Copyright © Junxiao Shi 2017” 

It seems that this option caused the removal of the Copyright line on title page, which is required in the template regardless of whether registering copyright.
